const categories = [
  'DEVELOPMENT',
  'WEB DESIGN',
  'APPLICATION',
  'DESIGN',
  'MOBILE',
];

const data = [
  {
    id: 1,
    year: '2022',
    date: '16/3/2022',
    category: 'Backend',
    title: 'e-Aktet',
    image: 'eaktettest.png',
    technologies: [],
    desc: `The government staff system project aimed to revolutionize and streamline the internal operations and processes within government institutions. As a key contributor to this project, I focused on developing a comprehensive and user-friendly system that would enhance productivity and collaboration among government staff members.Working closely with government officials and stakeholders, I conducted in-depth analysis of existing workflows and identified areas for improvement. Leveraging my expertise in system design and development, I crafted a robust and scalable solution tailored to the specific needs and requirements of the government staff.`,
    links: {},
  },
  {
    id: 2,
    year: '2022',
    date: '21/3/2022',
    category: 'Frontend',
    title: 'E-commerce',
    image: 'fe1.png',
    technologies: [],
    desc: `This project is an e-commerce store dedicated to manufacturing industrial and environmental safety products that are designed to promote workplace safety compliance. To create a professional and trustworthy online shopping experience, I developed a visually appealing and user-friendly interface. The design incorporates a clean and intuitive layout, allowing customers to easily browse through different categories of safety products. Clear product descriptions, specifications, and high-resolution images help customers make informed purchasing decisions. The website incorporates a secure payment gateway to ensure safe transactions, protecting sensitive customer information. `,
    links: {},
  },
  {
    id: 3,
    year: '2023',
    date: '22/12/2022',
    category: 'Frontend',
    title: 'E-commerce',
    image: 'fe2.png',
    technologies: [],
    desc: `The website features a wide range of protective outwear items, based in USA. For the design, I utilized modern and minimalist aesthetics to ensure a visually appealing and user-friendly experience. I incorporated responsive design principles to guarantee seamless navigation across different devices. To optimize the performance of the website, I implemented various techniques, including image optimization, caching strategies, and lazy loading. These measures ensure fast loading times and an overall smooth browsing experience for visitors.  I also implemented secure payment gateways to ensure a safe and convenient checkout process.
    `,
    links: {},
  },
  {
    id: 4,
    year: '2022',
    date: '04/5/2022',
    category: 'Backend',
    title: 'e-Albania',
    image: 'ealbaniatest.png',
    technologies: [],
    desc: `The government portal project represents a significant endeavor in transforming traditional public services into efficient and accessible electronic platforms. As part of the project, I focused on the intricate backend development to facilitate seamless operations and ensure optimal functionality. This involved implementing robust data management systems, integrating various databases, and establishing secure user authentication mechanisms.Collaboration with stakeholders and subject matter experts was integral to the success of this project. 
    `,
    links: {},
  },
  {
    id: 5,
    year: '2022',
    date: '05/02/2023',
    category: 'Frontend',
    title: 'E-commerce',
    image: 'fe3.png',
    technologies: [],
    desc: `The website serves as a platform for customers to explore and purchase a wide range of water systems and related products, including water filters, rainwater harvesting systems, efficient irrigation solutions, and water-saving devices. The goal is to provide customers with access to high-quality products that contribute to responsible water usage and environmental sustainability. 
    To create an engaging and user-friendly online shopping experience, I implemented a visually appealing design with intuitive navigation. The layout is designed to showcase product categories, highlight key features, and provide detailed product information. I incorporated an intuitive search functionality to help customers find specific items easily.`,
    links: {},
  },
  {
    id: 6,
    year: '2022',
    date: '11/11/2022',
    category: 'Backend',
    title: 'Universiteti i Tiranes',
    image: 'uttest.png',
    technologies: ['ReactJs', 'JS', 'Docusaurus ', 'Vercel', 'Responsive'],
    desc: `The Student Portal for the University of Tirana serves as a centralized digital platform designed to enhance the academic journey and overall student experience. Developed with the specific needs of University of Tirana students in mind, this comprehensive portal offers a wide range of features and functionalities.
    One of the key aspects of the Student Portal is its ability to provide easy access to essential academic information. Students can conveniently view their class schedules, exam timetables, and academic records. This empowers them to stay organized and plan their studies effectively, ensuring they make the most of their time at the university.
    `,
    links: {
      code: 'https://github.com/Tono2007/React-Libs',
      page: 'https://react-libs.vercel.app/',
    },
  },
  {
    id: 7,
    year: '2023',
    date: '11/11/2023',
    category: 'Backend',
    title: 'QKB',
    image: 'qkbtest.png',
    technologies: [],
    desc: `The National Business Center project serves as a comprehensive digital platform dedicated to supporting and streamlining the operations of government institutions responsible for business affairs. Developed with the goal of enhancing efficiency and facilitating a conducive business environment, this project provides a range of services and resources for businesses.At the core of the National Business Center is its commitment to simplifying administrative processes and reducing bureaucratic hurdles.
    `,
    links: {},
  },
  {
    id: 8,
    year: '2023',
    date: '05/08/2022',
    category: 'Backend',
    title: 'Website Analytics',
    image: 'analitics.png',
    technologies: [],
    desc: `'Website Analytics' is a privacy focused, web analytics software solution. It provides detailed web traffic reports, such as Realtime, Overview, Acquisitions, Behavior, Geographic, Technology, Events, and more.
    `,
    links: {},
  },
  {
    id: 9,
    year: '2023',
    date: '23/07/2023',
    category: 'Backend',
    title: 'Invoicing System',
    image: 'invoice.png',
    technologies: [],
    desc: `This is a web-based invoicing and client management system .Invoicer system will give you the opportunity to create custom invoices and send them to your clients directly, It will also helps in managing and tracking the income by the detailed reports it produces.
    `,
    links: {},
  },
  {
    id: 10,
    year: '2022',
    date: '27/11/2022',
    category: 'Backend',
    title: 'inventory Management System',
    image: 'inventory.png',
    technologies: [],
    desc: `Inventory Insight is a comprehensive inventory management solution designed to streamline your business operations. With a user-friendly interface, it offers a range of tools to monitor and optimize your inventory. From real-time stock levels and order tracking to detailed product analytics, Inventory Insight empowers you with the insights you need to make informed decisions. Say goodbye to inventory discrepancies and hello to efficient supply chain management.
    `,
    links: {},
  },
  {
    id: 11,
    year: '2022',
    date: '03/02/2022',
    category: 'Frontend',
    title: 'Billing System',
    image: 'billing.png',
    technologies: [],
    desc: `This platform is a Well Designed Business Billing & Accounting Solution. Application is packed with ton of features like Invoicing, Quotations, Purchase Orders, Inventory Management, Customer Management, Supplier management, Project Management, Accounts, Data & Reports, Employee Management with distinct user roles.
    `,
    links: {},
  },
  {
    id: 12,
    year: '2023',
    date: '10/08/2023',
    category: 'Frontend',
    title: 'Hireswipe',
    image: 'hire.png',
    technologies: [],
    desc: `HireSwipe is a comprehensive hiring platform designed to simplify the recruitment process for employers. Employers can effortlessly post job opportunities and manage candidates. The system's admin panel offers efficient tools for user management, job tracking, candidate management, and role management. By simplifying tasks such as user access control, job assignment, and candidate evaluation, HireSwipe aims to enhance recruitment efficiency and empower organizations to make informed hiring decisions with ease.
    `,
    links: {},
  },
  {
    id: 13,
    year: '2023',
    date: '10/08/2023',
    category: 'Backend',
    title: 'Workers Manager',
    image: 'worker.png',
    technologies: [],
    desc: `Workers Manager is powerful, yet simple, project and client management software application. It’s a perfect solution for freelance designers and developers. It also works great for consultants, project managers, and service professionals.
    `,
    links: {},
  },
  {
    id: 14,
    year: '2022',
    date: '13/12/2022',
    category: 'Backend',
    title: 'Human Resources',
    image: 'hr-management.png',
    technologies: [],
    desc: `This system was created with HR daily tasks in mind. With seamlessly integrated features including Employee and Department management, Awards tracking, Expense handling, Holidays planning, Attendance monitoring, Leave Applications processing, Leave Types customization, and a dynamic Notice Board.
    `,
    links: {},
  },
  {
    id: 15,
    year: '2022',
    date: '13/12/2022',
    category: 'Frontend',
    title: 'Learning Platform',
    image: 'academy.png',
    technologies: [],
    desc: `This was created as a marketplace for online learning. Here students and teachers are combined together for sharing knowledge through a structured course-based system. Teachers or instructors can create an unlimited number of courses, video lessons and documents according to their expertise and students can enroll in these courses and make themselves skilled anytime and from anywhere.
    `,
    links: {},
  },
  {
    id: 16,
    year: '2022',
    date: '13/12/2022',
    category: 'Frontend',
    title: 'CRM',
    image: 'crm.png',
    technologies: [],
    desc: `A simple application that helps improveing customer relationship to grow businesses more efficiently. You can manage your company’s associations in a friendly interface and with a low learning curve.
    `,
    links: {},
  },
  {
    id: 17,
    year: '2022',
    date: '13/12/2022',
    category: 'Frontend',
    title: 'Hotel Booking System',
    image: 'hotel.png',
    technologies: [],
    desc: `This is a system designed for managing a hotel. It provides management system for – coupons, amenities, categories, hotel rooms, hotel room bookings, tour packages, tour package bookings, withdrawals, transactions, support tickets, vendors , users , announcement popups, custom pages, languages, admin / role permission, monthwise earnings, monthwise profits, drag & drop menu builder,  sitemaps etc… 
    `,
    links: {},
  },
];

export default data;
